### ISSUE TITLE
Install FastReport Tools extension

### ISSUE THREAD

**Issue by Haytham510** [pirauvladislav/FastReportTools#2]
How to install FastReport Tools extension on Visual studio, Cannot find it in Visual studio marketplace.

![image](https://user-images.githubusercontent.com/75125295/131224021-099b659a-1e7b-4c37-9819-75089120f7d9.png)

**Comment by pirauvladislav** [comment]
Hi, you can download and run FastReport.Tools.vsix from FastReportTools/FastReport.Tools/bin/Release/ for now,
I haven't published it to marketplace yet.
